### ISSUE TITLE
Supreme does not load in minecraft versions above 1.20.2

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/Supreme#54]
## Description (Required)

see error report below

## Server Log / Error Report

[15:32:20 ERROR]: Error occurred while enabling Supreme vDEV - 29 (git f9e70053) (Is it up to date?)
java.lang.InstantiationError: org.bukkit.enchantments.EnchantmentWrapper
        at com.github.relativobr.supreme.util.EnchantsAndEffectsUtil.getEnchants(EnchantsAndEffectsUtil.java:123) ~[Supreme-29.jar:?]
        at com.github.relativobr.supreme.util.EnchantsAndEffectsUtil.addGearBasicEnchants(EnchantsAndEffectsUtil.java:104) ~[Supreme-29.jar:?]
        at com.github.relativobr.supreme.gear.AbstractWeapons.setup(AbstractWeapons.java:26) ~[Supreme-29.jar:?]
        at com.github.relativobr.supreme.setup.MainSetup.setup(MainSetup.java:26) ~[Supreme-29.jar:?]
        at com.github.relativobr.supreme.Supreme.onEnable(Supreme.java:172) ~[Supreme-29.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-405]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:32:20 INFO]: [Supreme] Disabling Supreme vDEV - 29 (git f9e70053)

## Environment (Required)

 - Minecraft Version:1.20.3 and .4
 - CS-CoreLib Version:  na
 - Slimefun Version:1133
 - Plugin Version: 29

**Comment by jefflima1** [comment]
I have this problem, is there any solution to start on 1.20.4 servers?

**Comment by Boomer-1** [comment]
this may be tied to the problems other addons are having due to spigot making a change. nothing you can do without fixing the code due to spigot

**Comment by RelativoBR** [comment]
Fix in:
- https://github.com/Slimefun-Addon-Community/Supreme/pull/56

**Comment by jefflima1** [comment]
Hello, where can I download the new version?

**Comment by Boomer-1** [comment]
it has not been added to blob builds yet. gotta wait till it is

**Comment by Boomer-1** [comment]
closed as completed with the latest on blob.build
